import {test,expect} from '@playwright/test';
test('room controls, reference photos and responsive scene',async({page})=>{
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{document.modelContext={registerTool(tool){window.designTool=tool}}});
await page.goto('http://127.0.0.1:5173/');
await expect(page.locator('canvas')).toBeVisible();
await page.waitForTimeout(2500);
await expect(page.getByText('£15,600',{exact:true})).toBeVisible();
await page.getByLabel('Width',{exact:true}).fill('6');
await expect(page.getByText('£23,400',{exact:true})).toBeVisible();
await page.getByLabel('Price per square metre').fill('1000');
await expect(page.getByText('£18,000',{exact:true})).toBeVisible();
expect(await page.evaluate(()=>window.designTool.execute().estimatedCost)).toBe(18000);
await page.getByLabel('Place room on lawn').click();
await page.locator('canvas').click({position:{x:430,y:230}});
await page.getByLabel('Place room on lawn').click();
await page.getByRole('button',{name:'Roof & openings',exact:true}).click();
await page.getByLabel('Roof style').selectOption('gable');
await page.getByLabel('Front canopy').check();
await page.getByRole('button',{name:'From patio',exact:true}).click();
await page.waitForTimeout(500);
await page.screenshot({path:'/tmp/garden-patio.png'});
await page.getByRole('button',{name:'Look at house',exact:true}).click();
await page.waitForTimeout(500);
await page.screenshot({path:'/tmp/garden-house.png'});
await page.getByRole('button',{name:'References',exact:true}).click();
await page.getByRole('button',{name:'Patio doors',exact:true}).click();
await expect(page.locator('.modal img')).toHaveAttribute('src','/patio.jpg');
await page.getByLabel('Close references').click();
await page.getByRole('button',{name:'Reset design'}).click();
await page.waitForTimeout(500);
await page.screenshot({path:'/tmp/garden-desktop.png'});
expect(errors).toEqual([]);
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'/tmp/garden-mobile.png'});
expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
