import React,{useMemo} from 'react';
import * as THREE from 'three';
import {Html,Line} from '@react-three/drei';
import {dimensions,thickness,wallSpan,electricalTypes,cableRoute} from './design.js';
import {useHover} from './useHover.js';
import LabelledGroup from './LabelledGroup.jsx';
const B=({p=[0,0,0],s=[1,1,1],c='#fff',recede=false,...rest})=><mesh position={p} castShadow receiveShadow {...rest}><boxGeometry args={s}/><meshStandardMaterial color={c} roughness={.8} polygonOffset={recede} polygonOffsetFactor={recede?2:0} polygonOffsetUnits={recede?2:0}/></mesh>;
export const wallTransform=(v,side,offset=0)=>side==='front'?{position:[0,0,v.depth/2-offset],rotation:[0,0,0]}:side==='back'?{position:[0,0,-v.depth/2+offset],rotation:[0,Math.PI,0]}:side==='left'?{position:[-v.width/2+offset,0,0],rotation:[0,-Math.PI/2,0]}:{position:[v.width/2-offset,0,0],rotation:[0,Math.PI/2,0]};
function Cap({points,t,c,p,recede=false}){const geometry=useMemo(()=>{const shape=new THREE.Shape();shape.moveTo(...points[0]);points.slice(1).forEach(q=>shape.lineTo(...q));shape.closePath();return new THREE.ExtrudeGeometry(shape,{depth:Math.max(.003,t),bevelEnabled:false})},[JSON.stringify(points),t]);return <mesh geometry={geometry} position={p} castShadow receiveShadow><meshStandardMaterial color={c} polygonOffset={recede} polygonOffsetFactor={recede?2:0} polygonOffsetUnits={recede?2:0}/></mesh>}
function WallSkin({v,side,offset,t,color,frame=false,insulation=false,onClick}){const d=dimensions(v),span=wallSpan(v,side),h=Math.max(.1,d.clear),holes=v.openings.filter(o=>o.enabled&&o.wall===side).map(o=>({u:o.u,width:o.width,y:o.y,height:o.height})),xs=[0,span,...holes.flatMap(o=>[o.u,o.u+o.width])].sort((a,b)=>a-b),ys=[0,h,...holes.flatMap(o=>[Math.min(h,o.y),Math.min(h,o.y+o.height)])].sort((a,b)=>a-b);const segments=[];for(let i=0;i<xs.length-1;i++)for(let j=0;j<ys.length-1;j++){const x0=xs[i],x1=xs[i+1],y0=ys[j],y1=ys[j+1];if(x1-x0<.001||y1-y0<.001||holes.some(o=>(x0+x1)/2>o.u&&(x0+x1)/2<o.u+o.width&&(y0+y1)/2>o.y&&(y0+y1)/2<o.y+o.height))continue;if(frame){for(let x=Math.ceil(x0/v.studSpacing)*v.studSpacing;x<=x1;x+=v.studSpacing)segments.push(<B key={'s'+i+j+x} p={[x-span/2,(y0+y1)/2+d.floorY,0]} s={[v.studWidth,y1-y0,t]} c={color}/>);for(const y of [y0+v.studWidth/2,y1-v.studWidth/2])segments.push(<B key={'r'+i+j+y} p={[(x0+x1)/2-span/2,y+d.floorY,0]} s={[x1-x0,v.studWidth,t]} c={color}/>)}else segments.push(<B key={i+','+j} p={[(x0+x1)/2-span/2,(y0+y1)/2+d.floorY,0]} s={[x1-x0,y1-y0,Math.max(t,.003)]} c={color} recede={insulation}/>)}let cap=null;if(v.roof!=='flat'&&d.rise>0){let top;if(v.roof==='gable'){const edge=d.rise*v.overhang/(v.width/2+v.overhang);top=(side==='front'||side==='back')?[[-span/2,edge],[0,d.rise],[span/2,edge]]:[[-span/2,edge],[span/2,edge]]}else{const low=d.rise*v.overhang/(v.depth+2*v.overhang),high=d.rise-low;top=side==='front'?[[-span/2,high],[span/2,high]]:side==='back'?[[-span/2,low],[span/2,low]]:side==='left'?[[-span/2,low],[span/2,high]]:[[-span/2,high],[span/2,low]]}cap=<Cap points={[[-span/2,0],...top,[span/2,0]]} t={t} c={color} p={[0,d.wallTop,-t/2]} recede={insulation}/>;}return <group {...wallTransform(v,side,offset)} onClick={onClick}>{segments}{cap}</group>}
function Opening({v,o,select}){const [hovered,hover]=useHover();const d=dimensions(v),span=wallSpan(v,o.wall),glassH=o.height-.12,glassW=o.width-.12;const parts=o.kind==='bifold'?o.panels: o.kind==='french'?2:1;return <group {...wallTransform(v,o.wall,-.015)} {...hover} onClick={e=>{e.stopPropagation();select('opening',o.id)}}><group position={[o.u+o.width/2-span/2,d.floorY+o.y+o.height/2,0]}>{[-1,1].map(sign=><React.Fragment key={sign}><B p={[sign*(o.width/2-.025),0,0]} s={[.05,o.height,.07]} c={o.color}/><B p={[0,sign*(o.height/2-.025),0]} s={[o.width,.05,.07]} c={o.color}/></React.Fragment>)}<group rotation={[o.kind==='window'?-o.open*Math.PI/180:0,0,0]}>{Array.from({length:parts},(_,i)=><group key={i} position={[-glassW/2+(i+.5)*glassW/parts,0,0]} rotation={[0,o.kind==='bifold'?(i%2?1:-1)*o.open*Math.PI/180:o.kind==='french'?(i===0?-1:1)*o.open*Math.PI/180:0]}><mesh><boxGeometry args={[glassW/parts-.025,glassH,.025]}/><meshStandardMaterial color="#8eb9bf" transparent opacity={.32} roughness={.15} metalness={.15}/></mesh><B p={[glassW/parts/2-.018,0,.005]} s={[.025,glassH,.045]} c={o.color}/></group>)}</group>{o.kind==='window'&&<B p={[0,o.height/2-.035,.055]} s={[o.width-.1,.03,.025]} c="#aeb4a9"/>}{hovered&&<Html position={[0,o.height/2+.15,0]} center><span className="dimension">{o.id} · {o.width.toFixed(2)} × {o.height.toFixed(2)} m</span></Html>}</group></group>}
function Fitting({v,e,select}){const [hovered,hover]=useHover();const d=dimensions(v),ceiling=e.surface==='ceiling',outside=e.type==='external'||e.type==='acOutdoor';const p=ceiling?[e.u-v.width/2,v.height-d.roof-d.rise-.025,e.z-v.depth/2]:[e.u-wallSpan(v,e.surface)/2,d.floorY+e.y,0];const group=ceiling?{}:wallTransform(v,e.surface,outside?-.055:d.wall+.025);return <group {...group} {...hover} onClick={ev=>{ev.stopPropagation();select('electrical',e.id)}}><group position={p}>{e.type==='internal'?<mesh><cylinderGeometry args={[e.width/2,e.width/2,.015,12]}/><meshStandardMaterial color={e.color} emissive="#ffe8ac" emissiveIntensity={.35}/></mesh>:e.type==='acIndoor'?<group><B s={[e.width,e.height,.045]} c={e.color}/><B p={[0,0,.03]} s={[e.width*.72,e.height*.22,.01]} c="#dfe3e8"/><B p={[0,-e.height*.18,.03]} s={[e.width*.58,e.height*.45,.008]} c="#c5cad1"/></group>:e.type==='acOutdoor'?<group><B s={[e.width,e.height,.08]} c={e.color}/><mesh position={[0,0,.05]} rotation={[Math.PI/2,0,0]}><circleGeometry args={[Math.min(e.width,e.height)*.32,16]}/><meshStandardMaterial color="#9aa1a8"/></mesh></group>:e.type==='consumer'?<group><B s={[e.width,e.height,.04]} c={e.color}/><B p={[0,0,.025]} s={[e.width*.85,e.height*.88,.01]} c="#4a5560"/></group>:<><B s={[e.width,e.height,.035]} c={e.color}/>{e.type==='socket'&&[-1,1].map(a=><B key={a} p={[a*.035,0,-.022]} s={[.025,.025,.007]} c="#4a514c"/>)}{e.type==='data'&&<B p={[0,0,-.022]} s={[.025,.02,.006]} c="#39494c"/>}</>}{hovered&&<Html position={[0,.2,0]} center><span className="dimension">{electricalTypes[e.type]} · {e.id}</span></Html>}</group></group>}
export function Construction({v,select=()=>{}}){const [roomHovered,roomHover]=useHover();const d=dimensions(v),exploded=v.roofView==='exploded',open=v.roofView==='removed',gap=exploded?v.explode:0;const visible=id=>v.layers.find(l=>l.id===id)?.enabled&&v.layers.find(l=>l.id===id)?.visible;const color=id=>v.layers.find(l=>l.id===id)?.color;const pick=id=>e=>{e.stopPropagation();select('layer',id)};const wallLayers=[['cladding',0],['membrane',thickness(v,'cladding')],['osb',thickness(v,'cladding')+thickness(v,'membrane')],['frame',thickness(v,'cladding')+thickness(v,'membrane')+thickness(v,'osb')],['wallInsulation',thickness(v,'cladding')+thickness(v,'membrane')+thickness(v,'osb')],['plaster',d.wall-thickness(v,'paint')-thickness(v,'plaster')],['paint',d.wall-thickness(v,'paint')]];const roofParts=[['ceiling',thickness(v,'ceiling')],['roofFrame',Math.max(thickness(v,'roofFrame'),thickness(v,'roofInsulation'))],['roofInsulation',Math.max(thickness(v,'roofFrame'),thickness(v,'roofInsulation'))],['roofDeck',thickness(v,'roofDeck')],['epdm',thickness(v,'epdm')]];let roofY=v.height-d.roof-d.rise;let floorY=v.base;return <group position={[v.x,exploded?1.2:0,v.setback+v.depth/2]} {...roomHover}>{roomHovered&&v.roofView==='closed'&&<Html position={[0,v.height*.45,v.depth/2+1.1]} center><span className="dimension room-label">{v.width.toFixed(1)} × {v.depth.toFixed(1)} m</span></Html>}
{visible('concrete')&&<B p={[0,v.base-thickness(v,'concrete')/2,0]} s={[v.width,thickness(v,'concrete'),v.depth]} c={color('concrete')} onClick={pick('concrete')}/>}
{visible('concrete')&&exploded&&Array.from({length:Math.floor(v.width/.3)},(_,i)=><B key={i} p={[i*.3-v.width/2,v.base+.008,0]} s={[.008,.008,v.depth]} c="#545c59"/>)}
{['floorFrame','floorInsulation','floorDeck','laminate'].map((id,i)=>{const t=thickness(v,id),y=id==='floorFrame'||id==='floorInsulation'?v.base+t/2:floorY+t/2;if(id!=='floorFrame')floorY+=id==='floorInsulation'?Math.max(t,thickness(v,'floorFrame')):t;return visible(id)&&<group key={id} position={[0,-gap*(4-i),0]} onClick={pick(id)}>{id==='floorFrame'?Array.from({length:Math.ceil(v.width/v.studSpacing)},(_,k)=><B key={k} p={[-v.width/2+k*v.studSpacing,y,0]} s={[v.studWidth,t,v.depth]} c={color(id)}/>):<B p={[0,y,0]} s={[v.width-.04,Math.max(t,.004),v.depth-.04]} c={color(id)} recede={id==='floorInsulation'}/>}</group>})}
{wallLayers.map(([id,offset],i)=>visible(id)&&['front','back','left','right'].map(side=>(v.cutaway&&side==='front')?null:<WallSkin key={id+side} v={v} side={side} offset={offset+thickness(v,id)/2-gap*(wallLayers.length-i)} t={thickness(v,id)} color={color(id)} frame={id==='frame'} insulation={id==='wallInsulation'} onClick={pick(id)}/>))}
{v.openings.filter(o=>o.enabled).map(o=><Opening key={o.id} v={v} o={o} select={select}/>)}
{!open&&roofParts.map(([id,t],i)=>{const y=roofY+t/2;if(id!=='roofFrame')roofY+=t;const roofHalf=(sign)=>{const run=(v.width+v.overhang*2)/2,rise=d.rise,angle=Math.atan2(rise,run);return <group key={sign} position={[sign*run/2,y+rise/2+gap*(i+1),0]} rotation={[0,0,-sign*angle]}><B s={[run/Math.cos(angle),Math.max(t,.004),v.depth+v.overhang*2]} c={color(id)} recede={id==='roofInsulation'}/></group>};return visible(id)&&<LabelledGroup key={id} onClick={pick(id)} label={exploded?<Html position={[v.width/2+.5,y+d.rise+gap*(i+1),0]}><span className="dimension">{v.layers.find(l=>l.id===id).name} · {t*1000} mm</span></Html>:null}>{v.roof==='gable'?[-1,1].map(roofHalf):<group position={[0,y+d.rise/2+gap*(i+1),0]} rotation={[v.roof==='pent'?-v.pitch*Math.PI/180:0,0,0]}>{id==='roofFrame'?Array.from({length:Math.ceil(v.width/v.studSpacing)},(_,k)=><B key={k} p={[-v.width/2+k*v.studSpacing,0,0]} s={[v.studWidth,t,v.depth+v.overhang*2]} c={color(id)}/>):<B s={[v.width+2*v.overhang,Math.max(t,.004),(v.depth+2*v.overhang)/Math.cos(v.roof==='pent'?v.pitch*Math.PI/180:0)]} c={color(id)} recede={id==='roofInsulation'}/>}</group>}</LabelledGroup>})}
{v.skirting&&['front','back','left','right'].map(side=><group key={side} {...wallTransform(v,side,d.wall+.01)} onClick={e=>{e.stopPropagation();select('finish','skirting')}}>{(()=>{let cursor=0;const segments=[];const doors=v.openings.filter(o=>o.enabled&&o.wall===side&&o.y<v.skirtingHeight).sort((a,b)=>a.u-b.u);for(const o of [...doors,{u:wallSpan(v,side),width:0}]){if(o.u>cursor)segments.push(<B key={cursor} p={[(cursor+o.u)/2-wallSpan(v,side)/2,d.floorY+v.skirtingHeight/2,0]} s={[o.u-cursor,v.skirtingHeight,.018]} c={v.skirtingColor}/>);cursor=Math.max(cursor,o.u+o.width)}return segments})()}</group>)}
{!open&&!exploded&&['front','back','left','right'].map(side=><group key={side} {...wallTransform(v,side,-v.overhang)} onClick={e=>{e.stopPropagation();select('finish','fascia')}}>{v.fascia&&<B p={[0,v.height-d.roof/2-d.rise,0]} s={[wallSpan(v,side)+2*v.overhang,d.roof,.02]} c={v.fasciaColor}/ >}{v.soffit&&<B p={[0,v.height-d.roof-d.rise,.02]} s={[wallSpan(v,side),.012,Math.max(.02,v.overhang)]} c={v.fasciaColor}/>}</group>)}
{v.gutter&&!open&&<group onClick={e=>{e.stopPropagation();select('finish','gutter')}}><B p={[0,v.height-d.roof/2-d.rise,-v.depth/2-v.overhang-.06]} s={[v.width+.1,.065,.09]} c={v.fasciaColor}/><B p={[v.width/2-.08,v.height/2,-v.depth/2-v.overhang-.06]} s={[.06,v.height-d.roof,.06]} c={v.fasciaColor}/></group>}
{v.deck&&<B p={[0,v.deckHeight/2,v.depth/2+v.deckDepth/2]} s={[v.width,v.deckHeight,v.deckDepth]} c="#b2a084" onClick={e=>{e.stopPropagation();select('finish','deck')}}/>}
{v.canopy&&<><B p={[0,v.height-.1,v.depth/2+v.canopyDepth/2]} s={[v.width,.1,v.canopyDepth]} c={v.roofColor}/>{[-1,1].map(i=><B key={i} p={[i*(v.width/2-.05),(v.height-.1)/2,v.depth/2+v.canopyDepth-.05]} s={[.08,v.height-.1,.08]} c={v.fasciaColor}/>)}</>}
{v.electrical.filter(e=>e.enabled).map(e=><Fitting key={e.id} v={v} e={e} select={select}/>)}
</group>}
function CableRoute({v,c,select}){const [hovered,hover]=useHover();const {points,length}=cableRoute(v,c);return <group {...hover} onClick={e=>{e.stopPropagation();select('cable',c.id)}}><Line points={points} color={c.id==='power'?'#d19341':'#598fb0'} lineWidth={2}/>{hovered&&<Html position={[c.routeX,.2,(c.fromZ+points[3][2])/2]}><span className="dimension">{c.name} · {length.toFixed(1)} m incl. allowance</span></Html>}</group>}
export function CableRoutes({v,select}){return v.cables.filter(c=>c.enabled).map(c=><CableRoute key={c.id} v={v} c={c} select={select}/>)}
