import React from 'react';
import {Html} from '@react-three/drei';
import {dimensions,wallSpan} from './design';
import {wallTransform} from './Construction';
const B=({p=[0,0,0],s=[1,1,1],c='#fff',rotation,...rest})=><mesh position={p} rotation={rotation} castShadow receiveShadow {...rest}><boxGeometry args={s}/><meshStandardMaterial color={c} roughness={.75}/></mesh>;
function Door({width,height,depth,hinge,open,color,handleColor}){return <group position={[hinge*width/2,0,depth/2]} rotation={[0,-hinge*open*Math.PI/180,0]}><B p={[-hinge*width/2,0,0]} s={[width-.01,height-.01,.02]} c={color}/><B p={[-hinge*(width-.08),0,.03]} s={[.03,.05,.03]} c={handleColor}/></group>}
function DeskContents({width,height,depth}){return <group><B p={[0,-height/2+.38,-depth/2+.28]} s={[Math.min(width-.1,.9),.04,Math.min(.5,depth-.1)]} c="#c7b18c"/><B p={[0,-height/2+.58,-depth/2+.06]} s={[.02,.35,.02]} c="#8f8f88"/><B p={[0,-height/2+.78,-depth/2+.06]} s={[.55,.35,.03]} c="#2b2b2b"/><B p={[0,-height/2+.4,-depth/2+.15]} s={[.13,.05,.13]} c="#c9c9c9"/></group>}
function StorageContents({width,height,depth,shelves}){const rows=Math.max(1,shelves),count=Math.min(8,rows*2),perRow=Math.ceil(count/rows);return <group>{Array.from({length:rows-1},(_,i)=><B key={'shelf'+i} p={[0,-height/2+(i+1)*height/rows,0]} s={[width-.06,.02,depth-.06]} c="#d8cfa9"/>)}{Array.from({length:count},(_,i)=>{const row=Math.floor(i/perRow);return <mesh key={'mat'+i} position={[-width/2+.16+(i%perRow)*.14,-height/2+height/rows*(row+.28),0]} rotation={[0,0,Math.PI/2]} castShadow><cylinderGeometry args={[.055,.055,Math.min(.5,depth-.12),10]}/><meshStandardMaterial color={i%3===0?'#bd7858':'#628b87'}/></mesh>})}</group>}
export default function Cupboards({v,select}){const d=dimensions(v);return <group position={[v.x,0,v.setback+v.depth/2]}>{v.cupboards.filter(c=>c.enabled).map(c=>{const span=wallSpan(v,c.wall);return <group key={c.id} {...wallTransform(v,c.wall,d.wall+c.depth/2)} onClick={e=>{e.stopPropagation();select('cupboard',c.id)}}><group position={[c.u+c.width/2-span/2,d.floorY+c.height/2,0]}><B s={[c.width,c.height,c.depth]} c={c.color}/>{c.kind==='desk'?<DeskContents width={c.width} height={c.height} depth={c.depth}/>:<StorageContents width={c.width} height={c.height} depth={c.depth} shelves={c.shelves}/>}{Array.from({length:c.doors},(_,i)=>{const doorWidth=c.width/c.doors,hinge=c.doors===1?1:(i===0?-1:1);return <group key={i} position={[-c.width/2+doorWidth*(i+.5),0,0]}><Door width={doorWidth} height={c.height} depth={c.depth} hinge={hinge} open={c.open} color={c.color} handleColor={c.handleColor}/></group>})}{v.selected===c.id&&<Html position={[0,c.height/2+.15,0]} center><span className="dimension">{c.id} · {c.width.toFixed(2)} × {c.depth.toFixed(2)} m</span></Html>}</group></group>})}</group>}
