import test from 'node:test';
import assert from 'node:assert/strict';
import {createDefault,normalize,total,dimensions,heightLimit,clearance,checkPlanning,checkBuildingRegs,openingProblems,cableRoute,eavesHeight,yogaLayouts,yogaProblems,cupboardProblems,freeYogaSlot,boundaryClearanceMin} from './design.js';
test('default placement keeps at least 1 m roof-edge clearance from boundaries',()=>{const v=normalize(createDefault());assert.ok(clearance(v)>=boundaryClearanceMin-.001);assert.ok(!checkBuildingRegs(v).some(c=>c.title.includes('Timber building near boundary')));});
test('quoted defaults, internal build-up and optional bifold cost',()=>{let v=normalize(createDefault());assert.equal(v.width,7.3);assert.equal(v.depth,4);assert.equal(total(v),40510);assert.equal(v.openings[0].width,1.6);assert.equal(v.openings.filter(o=>o.kind==='window').length,1);assert.equal(v.electrical.filter(e=>e.type==='internal').length,12);assert.equal(v.electrical.filter(e=>e.type==='external').length,7);assert.equal(v.electrical.filter(e=>e.type==='socket').length,8);assert.equal(v.cupboards.length,1);assert.ok(dimensions(v).clear>2);assert.ok(dimensions(v).internalArea<29.2);v.openings[0].kind='bifold';assert.equal(total(v),42510);v.openings[0].enabled=false;assert.equal(total(v),40510);});
test('height guard includes roof projections and moving nearer any boundary',()=>{let v=createDefault();v.height=3;v=normalize(v);assert.equal(v.height,2.5);v.width=3;v.depth=3;v.setback=3;v.roof='gable';v.pitch=25;v.height=3.2;v=normalize(v);assert.equal(heightLimit(v),4);assert.ok(eavesHeight(v)<=2.50001);v.setback=.5;v=normalize(v);assert.equal(v.height,2.5);v.height=4;v.x=3;v=normalize(v);assert.equal(v.height,2.5);v.deckHeight=.8;assert.equal(normalize(v).deckHeight,.3);});
test('unknown plot is never presented as a passed coverage check',()=>{const v=createDefault();const c=checkPlanning(v);assert.ok(c.some(c=>c.level==='unknown'&&c.title.includes('50%')));v.planning.plotArea=50;v.planning.otherArea=5;assert.ok(checkPlanning(v).some(c=>c.level==='danger'&&c.title.includes('Coverage')));v.planning.listed='yes';assert.ok(checkPlanning(v).some(c=>c.level==='danger'&&c.title==='Listed building'));});
test('planning and building regulations remain separate',()=>{const v=createDefault();v.setback=.5;assert.ok(checkBuildingRegs(v).some(c=>c.title.includes('Timber building near boundary')));assert.ok(!checkPlanning(v).some(c=>c.title.includes('Building regulations')));v.width=9;v.depth=5;assert.ok(checkBuildingRegs(v).some(c=>c.title.includes('Over 30')));v.planning.nation='Scotland';assert.ok(checkPlanning(v).some(c=>c.level==='unknown'&&c.title.includes('Jurisdiction')));});
test('openings overlap and height checks survive dimension changes',()=>{let v=createDefault();v.openings.push({...v.openings[0],id:'door-2'});assert.ok(openingProblems(v).some(x=>x.includes('overlaps')));v.openings[0].height=3;assert.ok(openingProblems(v).some(x=>x.includes('height')));v.width=2.5;v=normalize(v);for(const o of v.openings.filter(o=>o.wall==='front'))assert.ok(o.u+o.width<=v.width);});
test('shared cavities do not double-count frame and insulation',()=>{const v=createDefault();const before=dimensions(v);v.layers.find(l=>l.id==='frame').enabled=false;assert.equal(dimensions(v).wall,before.wall);v.layers.find(l=>l.id==='wallInsulation').mm=150;assert.ok(Math.abs(dimensions(v).wall-before.wall-.05)<1e-9);});
test('cable route matches wall orientation and includes slack',()=>{const v=createDefault(),c=v.cables[0];const r=cableRoute(v,c);assert.equal(r.points.at(-1)[0],v.x+v.width/2-c.toU);const before=r.length;c.slack+=3;assert.equal(cableRoute(v,c).length,before+3);});

test('higher pent-wall eaves are constrained independently of ridge height',()=>{let v=createDefault();v.width=3;v.depth=3;v.setback=3;v.roof='pent';v.pitch=15;v.height=3;v=normalize(v);assert.ok(eavesHeight(v)<=2.50001);assert.ok(v.height<2.55);});

test('yoga candidates fit the internal floor, keep teacher and avoid door zones',async()=>{const {yogaLayouts,yogaProblems}=await import('./design.js');const v=createDefault();const layouts=yogaLayouts(v,v.yoga);assert.ok(layouts.length>0);assert.ok(layouts[0].count>0);for(const layout of layouts){assert.equal(layout.items.filter(m=>m.teacher).length,1);assert.deepEqual(yogaProblems(v,{...v.yoga,items:layout.items}),[]);}const spacious=yogaLayouts(v,{...v.yoga,gap:.6});assert.ok(spacious[0].count<=layouts[0].count);});
test('disabling the teacher does not duplicate identical layouts',()=>{const v=createDefault();const layouts=yogaLayouts(v,{...v.yoga,teacher:false});const names=layouts.map(l=>l.name+JSON.stringify(l.items));assert.equal(new Set(names).size,names.length);assert.ok(layouts.every(l=>l.items.every(m=>!m.teacher)));});
test('diagonal and circle layouts rotate mats and stay valid',()=>{const v=createDefault();const layouts=yogaLayouts(v,v.yoga);const diagonal=layouts.filter(l=>l.id.startsWith('diagonal-'));const circle=layouts.filter(l=>l.id.startsWith('circle-'));assert.ok(diagonal.length>=2);assert.ok(circle.length>=2);assert.ok(diagonal.every(l=>l.items.filter(m=>!m.teacher).every(m=>Math.abs(m.rotation)===Math.PI/4)));assert.ok(circle.every(l=>l.items.filter(m=>!m.teacher).every(m=>Number.isFinite(m.rotation))));for(const layout of [...diagonal,...circle])assert.deepEqual(yogaProblems(v,{...v.yoga,items:layout.items}),[]);});
test('yoga mats are re-clamped inside the internal floor when the room shrinks',()=>{let v=createDefault();v.yoga.items=[{id:'student-0',teacher:false,x:6,z:3,w:.65,l:1.85}];v.width=3;v.depth=3;v=normalize(v);const m=v.yoga.items[0],iw=v.width-2*dimensions(v).wall,il=v.depth-2*dimensions(v).wall;assert.ok(m.x+m.w<=iw+1e-9);assert.ok(m.z+m.l<=il+1e-9);});
test('a free yoga slot never lands on an existing mat',()=>{const v=createDefault();const settings={...v.yoga,items:[{id:'a',teacher:false,x:0,z:0,w:.65,l:1.85}]};const slot=freeYogaSlot(v,settings,.65,1.85);assert.ok(slot.x>0||slot.z>0);});
test('default specification includes integrated storage cupboard and corner windows, flags overlaps',()=>{const v=normalize(createDefault());assert.equal(v.cupboards.length,1);assert.equal(v.cupboards[0].id,'cupboard');assert.equal(v.cupboards[0].wall,'back');assert.ok(v.cupboards[0].width>6.5);assert.ok(v.cupboards.every(c=>c.open===0));assert.equal(cupboardProblems(v).length,0);assert.ok(v.openings.some(o=>o.id==='window-front'&&o.wall==='front'&&o.u>6));assert.ok(!v.openings.some(o=>o.wall==='back'));assert.ok(v.electrical.some(e=>e.type==='acIndoor'&&e.surface==='right'));assert.ok(v.electrical.some(e=>e.type==='acOutdoor'&&e.surface==='right'));assert.ok(v.electrical.some(e=>e.type==='consumer'&&e.surface==='right'));v.cupboards[0].wall='front';v.cupboards[0].u=6.2;v.cupboards[0].width=1;assert.ok(cupboardProblems(normalize(v)).some(p=>p.includes('blocks')));});
test('yoga layouts keep mats clear of the storage cupboard',()=>{const v=createDefault();for(const layout of yogaLayouts(v,v.yoga))assert.ok(!yogaProblems(v,{...v.yoga,items:layout.items}).some(p=>p.includes('storage cupboard')));});
