import React, {useRef,useEffect,useLayoutEffect,useMemo} from 'react';
import {createRoot} from 'react-dom/client';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {OrbitControls,Html,Line,useTexture} from '@react-three/drei';
import {useHover} from './useHover.js';
import * as THREE from 'three';
import './style.css';
import Editor from './Editor';
import {dimensions,minSetback,minX,maxX,plotHalf,wallSpan} from './design.js';
import Yoga from './Yoga';
import Cupboards from './Cupboards';
import {Construction,CableRoutes,wallTransform} from './Construction';
function Box({p=[0,0,0],s=[1,1,1],c='#fff',rotation,...props}){return <mesh position={p} rotation={rotation} castShadow receiveShadow {...props}><boxGeometry args={s}/><meshStandardMaterial color={c} roughness={.85}/></mesh>}
function Tree({p,scale=1,color='#65784b'}){return <group position={p} scale={scale}><mesh position={[0,1.2,0]} castShadow><cylinderGeometry args={[.1,.19,2.4,7]}/><meshStandardMaterial color="#6d5943"/></mesh>{[[0,2.6,0,1.05],[-.65,2.25,.1,.8],[.7,2.5,.2,.83],[.1,3.25,.1,.8],[0,2.5,-.65,.85]].map(([x,y,z,r],i)=><mesh key={i} position={[x,y,z]} castShadow><icosahedronGeometry args={[r,1]}/><meshStandardMaterial color={color} flatShading/></mesh>)}</group>}
function Fence({length,p,rotate=false}){return <group position={p} rotation={[0,rotate?Math.PI/2:0,0]}><Box p={[0,.9,0]} s={[length,1.8,.08]} c="#756e5d"/>{Array.from({length:Math.ceil(length/.15)},(_,i)=><Box key={i} p={[-length/2+i*.15,.9,.047]} s={[.012,1.74,.012]} c="#555548"/>)}{Array.from({length:Math.ceil(length/1.8)+1},(_,i)=><Box key={i} p={[-length/2+Math.min(i*1.8,length),.93,0]} s={[.12,1.86,.15]} c="#b3b2a3"/>)}{[.35,1.45].map(y=><Box key={y} p={[0,y,-.07]} s={[length,.08,.08]} c="#696555"/>)}</group>}
function AnimatedWindowCat(){const group=useRef(),material=useRef(),texture=useTexture(import.meta.env.BASE_URL+'window-cat.png');texture.colorSpace=THREE.SRGBColorSpace;useFrame(({clock})=>{const t=clock.getElapsedTime()%13;let amount=0;if(t>6&&t<7.2)amount=(t-6)/1.2;else if(t>=7.2&&t<9.5)amount=1;else if(t>=9.5&&t<10.8)amount=1-(t-9.5)/1.3;const eased=amount*amount*(3-2*amount);if(group.current){group.current.position.y=-.35-eased*.42;group.current.visible=eased<.96}if(material.current)material.current.opacity=1-eased});return <group ref={group} position={[.16,-.35,.09]}><mesh><planeGeometry args={[.348,.422]}/><meshBasicMaterial ref={material} map={texture} transparent alphaTest={.04} toneMapped={false} depthWrite={false}/></mesh></group>}
function HouseModel({length}){
  const brick=useMemo(()=>{const c=document.createElement('canvas');c.width=256;c.height=256;const ctx=c.getContext('2d');ctx.fillStyle='#b9a58a';ctx.fillRect(0,0,256,256);for(let row=0;row<16;row++)for(let col=-1;col<5;col++){ctx.fillStyle=['#936b51','#a57b5c','#93664f','#a17154'][(row*3+col+8)%4];ctx.fillRect(col*64+(row%2)*32+1,row*16+1,61,13)}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(3,2);t.colorSpace=THREE.SRGBColorSpace;return t},[]);
  const block=(p,s)=><mesh position={p} castShadow receiveShadow><boxGeometry args={s}/><meshStandardMaterial map={brick}/></mesh>;
  const win=(x,y,z,w,h,cat=false)=><group position={[x,y,z]} rotation={[0,Math.PI,0]}><Box s={[w+.12,h+.12,.1]} c="#edece2"/><Box p={[0,0,.065]} s={[w,h,.04]} c="#577d88"/>{cat&&<AnimatedWindowCat/>}<Box p={[0,0,.1]} s={[.065,h,.04]} c="#fff"/></group>;
  return <group position={[0,0,length+3]} scale={[-1,1,1]}>
    {block([0,2.8,0],[8,5.6,5])}{block([0,1.45,-3.1],[8,2.9,1.7])}<Box p={[0,2.98,-3.1]} s={[8.35,.18,2]} c="#434948"/>
    {[-2.45,0,2.1].map((x,i)=><React.Fragment key={x}>{win(x,4.35,-2.56,i===1?.65:1.45,1.25,i===1)}</React.Fragment>)}
    {win(-2,1.65,-4,2,1.45)}{win(2,1.15,-4,1.9,2.2)}<Box p={[0,6.2,-1.3]} s={[8.5,.18,3.2]} rotation={[-.46,0,0]} c="#626563"/><Box p={[0,6.2,1.3]} s={[8.5,.18,3.2]} rotation={[.46,0,0]} c="#626563"/>{block([1.1,6.7,.2],[.65,1.6,.7])}<Box p={[-3.82,1.5,-4.05]} s={[.08,3,.08]} c="#353f3b"/>
  </group>
}
function Glazing({p,w,h}){return <group position={p}><Box s={[w+.08,h+.08,.1]} c="#303b37"/><Box p={[0,0,.07]} s={[w-.09,h-.09,.04]} c="#8cbbc1"/><Box p={[0,0,.1]} s={[.045,h,.04]} c="#303b37"/><Box p={[w/2-.13,-.05,.13]} s={[.035,.22,.03]} c="#d4d9d0"/></group>}
function Surroundings({v}){return <>
<group position={[0,0,-6]}><Box p={[0,2.6,0]} s={[8,5.2,5]} c="#a18c70"/><Box p={[0,6.05,-1.3]} s={[8.4,.14,3.2]} rotation={[-.57,0,0]} c="#737779"/><Box p={[0,6.05,1.3]} s={[8.4,.14,3.2]} rotation={[.57,0,0]} c="#737779"/>{[-2.2,2.2].map(x=><Glazing key={x} p={[x,3.8,2.58]} w={.8} h={1.1}/>)}</group>
<group position={[9,0,-4]}><Box p={[0,2.8,0]} s={[6,5.6,7]} c="#987962"/><Box p={[-1.5,6.4,0]} s={[3.6,.16,7.4]} rotation={[0,0,.55]} c="#737779"/><Box p={[1.5,6.4,0]} s={[3.6,.16,7.4]} rotation={[0,0,-.55]} c="#737779"/></group>
<group position={[4,0,v.length-7]}><Box p={[0,.06,0]} s={[1.7,.12,2.5]} c="#adad94"/><mesh position={[0,.9,0]}><boxGeometry args={[1.6,1.7,2.4]}/><meshStandardMaterial color="#c0d5ca" transparent opacity={.22} depthWrite={false}/></mesh>{[-.8,.8].map(x=>[-1.2,0,1.2].map(z=><Box key={x+','+z} p={[x,.9,z]} s={[.045,1.8,.045]} c="#c8cfc6"/>))}{[-1.2,1.2].map(z=><React.Fragment key={z}><Box p={[0,1.8,z]} s={[1.6,.045,.045]} c="#c8cfc6"/>{[-1,1].map(side=><Box key={side} p={[side*.4,2.1,z]} s={[1,.045,.045]} rotation={[0,0,-side*.65]} c="#c8cfc6"/>)}</React.Fragment>)}<Box p={[0,2.4,0]} s={[.05,.05,2.45]} c="#c8cfc6"/>{[-1,1].map(side=><mesh key={side} position={[side*.4,2.1,0]} rotation={[0,0,-side*.65]}><boxGeometry args={[1,.025,2.4]}/><meshStandardMaterial color="#d2e0d4" transparent opacity={.35}/></mesh>)}</group>
<Tree p={[-3.8,0,v.length*.57]} scale={1.05} color="#667a50"/>
<Box p={[.8,.35,v.length-3.3]} s={[7.8,.7,.17]} c="#a29072"/>
<group position={[1.45,0,v.length*.48]}><Box p={[0,1.2,0]} s={[.04,2.4,.04]} c="#434d44"/><Box p={[0,2.2,0]} s={[.65,.035,.035]} c="#434d44"/>{[-.3,.3].map(x=><Box key={x} p={[x,1.95,0]} s={[.12,.35,.12]} c="#576257"/>)}</group>
</>}
function RoomDimensions({v}){if(!v.showDimensions)return null;const y=.16,z=v.setback+v.depth+.55,x=v.x+v.width/2+.55,color='#567247';return <group><Line points={[[v.x-v.width/2,y,z],[v.x+v.width/2,y,z]]} color={color}/><Html position={[v.x,y,z]} center><span className="dimension">{Math.round(v.width*100)} cm</span></Html><Line points={[[x,y,v.setback],[x,y,v.setback+v.depth]]} color={color}/><Html position={[x,y,v.setback+v.depth/2]} center><span className="dimension">{Math.round(v.depth*100)} cm</span></Html><Line points={[[v.x-v.width/2-.3,0,v.setback+v.depth/2],[v.x-v.width/2-.3,v.height,v.setback+v.depth/2]]} color={color}/><Html position={[v.x-v.width/2-.3,v.height/2,v.setback+v.depth/2]} center><span className="dimension">{Math.round(v.height*100)} cm</span></Html></group>}
function buildingFocus(v){const cx=v.x,cz=v.setback+v.depth/2,span=Math.max(v.width,v.depth,6),lift=v.roofView==='exploded'?v.explode*14:0;return {cx,cy:v.height*.42+(v.roofView==='exploded'?1.2:0),cz,span:span+lift}}
function cupboardFocus(v){const c=v.cupboards?.[0],d=dimensions(v);if(!c)return null;const span=wallSpan(v,c.wall),tr=wallTransform(v,c.wall,d.wall+c.depth/2),local=new THREE.Vector3(c.u+c.width/2-span/2,d.floorY+c.height/2,0),rotation=new THREE.Euler(...tr.rotation),target=local.applyEuler(rotation).add(new THREE.Vector3(v.x+tr.position[0],tr.position[1],v.setback+v.depth/2+tr.position[2])),inside=new THREE.Vector3(0,.03,-1).applyEuler(rotation);const roomSpan=(c.wall==='left'||c.wall==='right')?v.width-2*d.wall:v.depth-2*d.wall,desired=Math.max(2.2,c.width*1.3),distance=Math.min(desired,Math.max(1.4,roomSpan-c.depth-.6));return {target,position:target.clone().add(inside.multiplyScalar(distance)).add(new THREE.Vector3(0,.15,0))}}
function applyViewPreset(view,v,camera,controls){const c=controls.current;if(!c)return;const z=v.setback+v.depth/2;if(v.isolated){if(view==='cupboard'){const focus=cupboardFocus(v);if(focus){camera.position.copy(focus.position);c.target.copy(focus.target);c.update();return}}const {cx,cy,cz,span}=buildingFocus(v);const dist=span*2;if(view==='plan'){camera.position.set(cx,cy+dist*1.4,cz+.01);c.target.set(cx,0,cz)}else{camera.position.set(cx+dist*.75,cy+dist*.5,cz+dist*.72);c.target.set(cx,cy,cz)}c.update();return}if(view==='detail'){camera.position.set(v.x+10,9,z+11);c.target.set(v.x,1,z)}else if(view==='patio'){camera.position.set(2,1.65,v.length-1.1);c.target.set(v.x,1.3,z)}else if(view==='room'){camera.position.set(v.x,1.65,z+v.depth/2+1);c.target.set(0,2,v.length)}else if(view==='plan'){camera.position.set(v.x,33,v.length/2+.01);c.target.set(v.x,0,v.length/2)}else{camera.position.set(v.x+17,19,v.length/2+8);c.target.set(v.x,0,v.length/2)}c.update()}
function ViewControl({view,v,controls,recenterTick}){const {camera}=useThree();const wasIsolated=useRef(false);const isolatedDimsKey=v.isolated?[v.x,v.setback,v.depth,v.width,v.height,v.roofView,v.explode,v.cupboards?.[0]?.wall,v.cupboards?.[0]?.depth].join(','):null;useLayoutEffect(()=>{let raf,cancelled=false;const apply=()=>{if(cancelled)return;if(!controls.current){raf=requestAnimationFrame(apply);return}const entering=v.isolated&&!wasIsolated.current;const leaving=!v.isolated&&wasIsolated.current;wasIsolated.current=v.isolated;if(entering){applyViewPreset(view==='cupboard'?'cupboard':'detail',v,camera,controls);return}if(leaving)return;const preset=v.isolated?(view==='plan'?'plan':view==='cupboard'?'cupboard':'detail'):view;applyViewPreset(preset,v,camera,controls)};apply();return()=>{cancelled=true;if(raf)cancelAnimationFrame(raf)}},[view,recenterTick,v.isolated,isolatedDimsKey]);return null}
function CameraZoom({controls,zoomTick,zoomDir}){useEffect(()=>{const c=controls.current;if(!c||!zoomTick)return;zoomDir==='in'?c.dollyIn(1.28):c.dollyOut(1.28);c.update()},[zoomTick,zoomDir,controls]);return null}
function PlotBoundary({v}){const [hovered,hover]=useHover();const half=plotHalf(v);return <group {...hover}><Line points={[[-half,.15,-.65],[half,.15,-.65]]} color="#536c43" lineWidth={1}/>{[-half,half].map(x=><Line key={x} points={[[x,.15,-.9],[x,.15,-.4]]} color="#536c43"/>)}<mesh position={[0,.15,-.7]} rotation={[-Math.PI/2,0,0]} visible={false}><planeGeometry args={[v.plotWidth,.5]}/></mesh>{hovered&&<Html position={[0,.18,-.7]} center><span className="dimension">{v.plotWidth.toFixed(1)} m rear boundary</span></Html>}</group>}
function Scene({v,view,moving,movingMat,set,select,patchCupboard,moveMat,finishMatMove,recenterTick,zoomTick,zoomDir}){
  const controls=useRef(),half=plotHalf(v),plotW=v.plotWidth,tiles=Math.floor(plotW),cameraEnabled=!moving&&!movingMat;
  return <Canvas shadows camera={{position:[17,19,30],fov:43}} gl={{preserveDrawingBuffer:true}}>
    <color attach="background" args={['#e8eddf']}/><ambientLight intensity={1.1}/><hemisphereLight args={['#f7fbeb','#859479',1.3]}/><directionalLight position={[-10,20,12]} intensity={2.3} castShadow shadow-mapSize={[2048,2048]} shadow-camera-left={-25} shadow-camera-right={25} shadow-camera-top={35} shadow-camera-bottom={-25} shadow-bias={-.001}/>
    {!v.isolated&&<group><Box p={[0,-.2,v.length/2]} s={[plotW+.3,.4,v.length]} c="#93a36c"/><Box p={[0,-.42,v.length/2+1]} s={[plotW+2,.1,v.length+10]} c="#b9bda2"/><Box p={[0,.01,v.length-2]} s={[plotW,.08,4]} c="#bcbaa6"/>{Array.from({length:tiles},(_,i)=><Box key={i} p={[-plotW/2+(i+.5)*plotW/tiles,.056,v.length-2]} s={[.012,.012,4]} c="#a5a791"/>)}<Box p={[-half+.2,.025,v.length/2]} s={[.85,.07,v.length-4]} c="#b6b29a"/><Fence length={plotW} p={[0,0,0]}/><Fence length={v.length} p={[-half,0,v.length/2]} rotate/><Fence length={v.length} p={[half,0,v.length/2]} rotate/><HouseModel length={v.length}/><Tree p={[-half-.5,0,2]} scale={1.6}/><Tree p={[-half-.8,0,6]} scale={1.25}/>{v.featureTree&&<Tree p={[2.3,0,2.8]} scale={.95} color="#7b9551"/>}{[-2,-.8,.3,1.5].map((x,i)=><Tree key={x} p={[x,0,v.length-4]} scale={.35} color={i%2?'#a4ad54':'#718249'}/>)}<Box p={[4,1.2,v.length-4.5]} s={[1.6,2.4,2.4]} c="#536155"/><Box p={[4,2.44,v.length-4.5]} s={[1.8,.12,2.6]} c="#414941"/><group position={[1,0,v.length*.56]}><mesh position={[0,.4,0]}><cylinderGeometry args={[.1,.19,.8,12]}/><meshStandardMaterial color="#999d8b"/></mesh><mesh position={[0,.83,0]}><cylinderGeometry args={[.4,.3,.12,20]}/><meshStandardMaterial color="#aeb3a3"/></mesh><mesh position={[0,.9,0]} rotation={[-Math.PI/2,0,0]}><circleGeometry args={[.32,24]}/><meshStandardMaterial color="#89a9ac"/></mesh></group><Surroundings v={v}/></group>}
    <Construction v={v} select={select}/><Cupboards v={v} select={select}/>
    {view!=='cupboard'&&<Yoga v={v} select={select} movingMat={movingMat} moveMat={moveMat} finishMatMove={finishMatMove}/>}
    {!v.isolated&&<CableRoutes v={v} select={select}/>} {view!=='cupboard'&&<RoomDimensions v={v}/>}
    {v.grid&&!v.isolated&&<group>{Array.from({length:tiles+1},(_,i)=><Line key={'x'+i} points={[[-half+i*plotW/tiles,.076,0],[-half+i*plotW/tiles,.076,v.length]]} color="#a9b790" lineWidth={.5}/>)}{Array.from({length:v.length+1},(_,i)=><Line key={'z'+i} points={[[-half,.076,i],[half,.076,i]]} color="#a9b790" lineWidth={.5}/>)}</group>}
    {moving&&!v.isolated&&<mesh rotation={[-Math.PI/2,0,0]} position={[0,.12,v.length/2]} onPointerDown={e=>{e.stopPropagation();set('x',Math.max(minX(v),Math.min(maxX(v),e.point.x)));set('setback',Math.max(minSetback(v),Math.min(v.length-v.depth-4,e.point.z-v.depth/2)))}} onPointerMove={e=>{if(e.buttons===1){e.stopPropagation();set('x',Math.max(minX(v),Math.min(maxX(v),e.point.x)));set('setback',Math.max(minSetback(v),Math.min(v.length-v.depth-4,e.point.z-v.depth/2)))}}}><planeGeometry args={[plotW,v.length]}/><meshBasicMaterial transparent opacity={0} depthWrite={false}/></mesh>}
    {!v.isolated&&<PlotBoundary v={v}/>} {v.isolated&&<mesh rotation={[-Math.PI/2,0,0]} position={[v.x,-0.02,v.setback+v.depth/2]} receiveShadow><planeGeometry args={[Math.max(v.width,v.depth)+4,Math.max(v.width,v.depth)+4]}/><meshStandardMaterial color="#d4d9cf"/></mesh>}
    <OrbitControls ref={controls} enableRotate={cameraEnabled} enablePan={cameraEnabled} enableZoom={cameraEnabled} makeDefault enableDamping dampingFactor={0.08} rotateSpeed={0.7} zoomSpeed={1.35} panSpeed={0.9} screenSpacePanning zoomToCursor minDistance={3} maxDistance={55} maxPolarAngle={Math.PI/2-.015} touches={{ONE:THREE.TOUCH.ROTATE,TWO:THREE.TOUCH.DOLLY_PAN}} mouseButtons={{LEFT:THREE.MOUSE.ROTATE,MIDDLE:THREE.MOUSE.DOLLY,RIGHT:THREE.MOUSE.PAN}}/><ViewControl view={view} v={v} controls={controls} recenterTick={recenterTick}/><CameraZoom controls={controls} zoomTick={zoomTick} zoomDir={zoomDir}/>
  </Canvas>
}
createRoot(document.getElementById('root')).render(<Editor Scene={Scene}/>);
